### ISSUE TITLE
Publish R-code/rmd files

### ISSUE THREAD

**Issue by LaurenzMar** [nz-stefan/blog-explorer#1]
Hello, 
I found the website via the Shiny competition and the website looks fabulous! 
I am somewhat new to rmarkdown, shiny and HTML, but I wanted to learn how to use HTML templates to make the app/website look nicer. However, the information on the web is somehow a bit scarce on this topic, so I would appreciate it if I could see your R-code and try to learn from it. 
I would be very glad if could have a peek and see how the integration of the Titan Template works. 

Best regards,
Laurenz

**Comment by nz-stefan** [comment]
Hi Laurenz,
Thanks for the kind words. Appreciated! 

All code to run the app is already in this repo. The html template itself is located [here](https://github.com/nz-stefan/blog-explorer/tree/master/app/www). I essentially copied the Titan template into this folder (and deleted a few folders and files that were not relevant). Check out the [index.html](https://github.com/nz-stefan/blog-explorer/blob/master/app/www/index.html) file, it contains variables (e.g. [{{ last refresh }}](https://github.com/nz-stefan/blog-explorer/blob/master/app/www/index.html#L103) which are replaced by actual content in [ui.R](https://github.com/nz-stefan/blog-explorer/blob/master/app/ui.R). 

A good introduction to creating HTML based Shiny apps can be found on the [RStudio doc page](https://shiny.rstudio.com/articles/templates.html). They use an example template there that is not very pretty but it demonstrates the general approach.

Hope that gives you enough direction to create some fancy Shiny apps yourself.

Stefan

**Comment by LaurenzMar** [comment]
Hello Stefan, 

thank you very much for the explanation and the link. I really appreciate it!

Best regards, 
Laurenz
